### PR TITLE
New examples

### PR DESCRIPTION
**Pull request by FBohnen**
Added:
- influxdb2.x
- Nginx Proxy Manager

### CODE REVIEW

**Comment by ryecoaaron** [comment]
Can you update the influxdb2.x to just be influxdb2 to match the yml filename?

**Comment by FBohnen** [comment]
Done

Am 9. August 2023 12:46:09 MESZ schrieb Aaron Murray ***@***.***>:

**Comment by FBohnen** [comment]
Changed folder /influxdb2.x to /influxdb2

**Comment by ryecoaaron** [comment]
should be available now.

**Pull request merged**
